### ISSUE TITLE
Create 2015 website

### ISSUE THREAD

**Issue by brookingcharlie** [HealthHackAu2015/HealthHack2014#1]
http://www.healthhack.com.au is written in a Ruby static-site framework, “middleman”

Currently a “billboard” advertising the event

Todo:
- the ad
- move content from 2014 to 2015 site
- sections describing all the pre-defined problems
- past winners
- about
- organisers
- sponsors
- per city tabs
- mobile rendering of site (scaling down)
- make a new logo

Integrates with:
- Twitter #healthhack
- Google Maps for event locations
- Disqus for comments

Currently hosted on AWS

Website code is open-source, hosted on GitHub incl. Issues.

**Comment by mscook** [comment]
Moved to - https://github.com/HealthHackAu/website-2015/issues
